#@data/values
---
namespace: kapp-controller
packaging_global_namespace: kapp-controller-packaging-global
create_namespace: true
create_packaging_namespace: true
#! clusters version 1.19 and below should disable APIPriorityAndFairness by setting the below to false
enable_api_priority_and_fairness: true

dangerous_enable_pprof: false

push_images: true
image_cache: true
image_repo: docker.io/showpune/kapp-controller-test

api_port: 10350
work_namespace: cluster
kapp_controller_version: "develop"
